<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>LiftAndShift.Domain</RootNamespace>
    <AssemblyName>LiftAndShift.Domain</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Ardalis.SmartEnum" />
    <PackageReference Include="MediatR.Contracts" />
  </ItemGroup>

</Project>
