<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <RootNamespace>LiftAndShift.AcceptanceTestHost</RootNamespace>
        <AssemblyName>LiftAndShift.AcceptanceTestHost</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Hosting.Testing" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\AppHost\AppHost.csproj" />
        <ProjectReference Include="..\..\src\Shared\Shared.csproj" />
    </ItemGroup>

</Project>
