<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>LiftAndShift.Shared</RootNamespace>
    <AssemblyName>LiftAndShift.Shared</AssemblyName>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" />
  </ItemGroup>

</Project>
