// <auto-generated />
using System;
using LiftAndShift.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LiftAndShift.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260921032031_AddWorkWeightConsecutiveFailures")]
    partial class AddWorkWeightConsecutiveFailures
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("LiftAndShift.Core.ContributorAggregate.Contributor", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Contributors");
                });

            modelBuilder.Entity("LiftAndShift.Core.FamilyMemberAggregate.FamilyMember", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pin")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FamilyMembers");
                });

            modelBuilder.Entity("LiftAndShift.Core.ProgrammeAggregate.Programme", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FamilyMemberId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrainingPhase")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Programmes");
                });

            modelBuilder.Entity("LiftAndShift.Core.WorkWeightAggregate.WorkWeight", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FamilyMemberId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Lift")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("WeightKg")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FamilyMemberId", "Lift")
                        .IsUnique();

                    b.ToTable("WorkWeights");
                });

            modelBuilder.Entity("LiftAndShift.Core.WorkoutSessionAggregate.LoggedSet", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Lift")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RepsAchieved")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SetNumber")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("WeightKg")
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkoutSessionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutSessionId");

                    b.ToTable("LoggedSets");
                });

            modelBuilder.Entity("LiftAndShift.Core.WorkoutSessionAggregate.WorkoutSession", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FamilyMemberId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("PerformedOn")
                        .HasColumnType("TEXT");

                    b.Property<int>("TrainingPhase")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Workout")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("WorkoutSessions");
                });

            modelBuilder.Entity("LiftAndShift.Core.ContributorAggregate.Contributor", b =>
                {
                    b.OwnsOne("LiftAndShift.Core.ContributorAggregate.PhoneNumber", "PhoneNumber", b1 =>
                        {
                            b1.Property<int>("ContributorId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Extension")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("ContributorId");

                            b1.ToTable("Contributors");

                            b1.WithOwner()
                                .HasForeignKey("ContributorId");
                        });

                    b.Navigation("PhoneNumber");
                });

            modelBuilder.Entity("LiftAndShift.Core.WorkoutSessionAggregate.LoggedSet", b =>
                {
                    b.HasOne("LiftAndShift.Core.WorkoutSessionAggregate.WorkoutSession", null)
                        .WithMany("LoggedSets")
                        .HasForeignKey("WorkoutSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LiftAndShift.Core.WorkoutSessionAggregate.WorkoutSession", b =>
                {
                    b.Navigation("LoggedSets");
                });
#pragma warning restore 612, 618
        }
    }
}
